databases:
  - name: team_crm
    databaseName: team_crm
    user: crm

services:
  - type: web
    name: team_crm
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: team_crm
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
